set(_CATKIN_CURRENT_PACKAGE "object_tracking")
set(object_tracking_MAINTAINER "edrone <edrone@todo.todo>")
set(object_tracking_DEPRECATED "")
set(object_tracking_VERSION "0.0.0")
set(object_tracking_BUILD_DEPENDS "ardrone_autonomy" "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(object_tracking_RUN_DEPENDS "ardrone_autonomy" "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(object_tracking_BUILDTOOL_DEPENDS "catkin")