set(_CATKIN_CURRENT_PACKAGE "control")
set(control_MAINTAINER "edrone <edrone@todo.todo>")
set(control_DEPRECATED "")
set(control_VERSION "0.0.0")
set(control_BUILD_DEPENDS "ardrone_autonomy" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(control_RUN_DEPENDS "ardrone_autonomy" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(control_BUILDTOOL_DEPENDS "catkin")