set(_CATKIN_CURRENT_PACKAGE "color_tracking")
set(color_tracking_MAINTAINER "edrone <edrone@todo.todo>")
set(color_tracking_DEPRECATED "")
set(color_tracking_VERSION "0.0.0")
set(color_tracking_BUILD_DEPENDS "ardrone_autonomy" "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(color_tracking_RUN_DEPENDS "ardrone_autonomy" "cv_bridge" "geometry_msgs" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(color_tracking_BUILDTOOL_DEPENDS "catkin")